// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYFUaOBJp831spvzdAlPjoYO7BkbWa_Y',
    appId: '1:762629349817:web:72b1a288c9bfa0eba95668',
    messagingSenderId: '762629349817',
    projectId: 'quiz-8ab5b',
    authDomain: 'quiz-8ab5b.firebaseapp.com',
    storageBucket: 'quiz-8ab5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ufKNeY6YqmhZ7z4BwiSIaeGoHoJ0YmA',
    appId: '1:762629349817:android:2d52edca00b84448a95668',
    messagingSenderId: '762629349817',
    projectId: 'quiz-8ab5b',
    storageBucket: 'quiz-8ab5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgF83NPc06HaWfsZ5nnNe4qN8vV1_c-F8',
    appId: '1:762629349817:ios:1f98d794fefc22baa95668',
    messagingSenderId: '762629349817',
    projectId: 'quiz-8ab5b',
    storageBucket: 'quiz-8ab5b.appspot.com',
    iosClientId: '762629349817-kuoevbqtp0mh1l9b67e4l285a9fb2vkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgF83NPc06HaWfsZ5nnNe4qN8vV1_c-F8',
    appId: '1:762629349817:ios:ec4f513f0df884a9a95668',
    messagingSenderId: '762629349817',
    projectId: 'quiz-8ab5b',
    storageBucket: 'quiz-8ab5b.appspot.com',
    iosClientId: '762629349817-csggp8gppkakdddshki2q44ubd0d96ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
